apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  # StorageBucket names must be globally unique. Replace <PROJECT_ID> with your project ID.
  name: <PROJECT_ID>-krm-trainig-bucket
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/project-id: <PROJECT_ID>
spec:
  storageClass: standard
  uniformBucketLevelAccess: true
  versioning:
    enabled: false
  location: us-central1