apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  # StorageBucket names must be globally unique. Replace <PROJECT_ID> with your project ID.
  name: <PROJECT_ID>-krm-trainig-bucket-asia
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/project-id: project-id
spec:
  storageClass: standard
  uniformBucketLevelAccess: true
  versioning:
    enabled: false
  location: asia-southeast1